applications:
  elate-me:
    enabled: false
    domain: elate.me
    image:
      repository: images.elate.me/elate-me
      digest: sha256:f98fa3197b5f31df8ded93d97ae62044fb8d0a8a22ac76de849b69904475b121
    containerPort: 8080
    healthPath: /
    runAsUser: 1000
    readOnlyRootFilesystem: false
    autoscaling:
      enabled: false

  elate-biz:
    enabled: false
    domain: elate.biz
    image:
      repository: images.elate.me/elate-biz
      digest: sha256:1afc7c6f448106c5bbecac561052cfa819d4fa0c596aaae8778f6a97534d4040
    containerPort: 8080
    healthPath: /healthz
    runAsUser: 101
    readOnlyRootFilesystem: true
    autoscaling:
      enabled: false
